name: chestLock2
version: '1.3'
main: org.GamerX.chestLock2.ChestLock2
api-version: '1.21'
commands:
  claim:
    description: use /claim [USERNAME] to claim the chest for the given player
    usage: /<command>
  global:
    description: use /global to make the chest you are looking at a global chest
    usage: /<command>
  nv:
    description: Give Night Vision to all players
    usage: /<command>
  fr:
    description: Give Fire Resistance to all players
    usage: /<command>
  reg:
    description: Give Fire Resistance to all players
    usage: /<command>